In [2]:
import numpy as np

c = np.array([2,4,5], dtype="int16")
print(c)

[2 4 5]


In [ ]:
#2-D Array
d=np.array([[3.5,4.0,5.4,5.3],[1.2,8.0,9.0,6.0]])
print(d)

[[3.5 4.  5.4 5.3]
 [1.2 8.  9.  6. ]]


In [ ]:
#Get Dimension
d.ndim

2

In [ ]:
# Get Shape
d.shape

(2, 4)

In [ ]:
# Get Type
d.dtype
c.dtype

dtype('int16')

In [ ]:
# Get Size
d.itemsize

8

In [ ]:
# Get Total Size
d.nbytes

64

In [ ]:
v= np.array([[1,3,4,5,6,6,7,4],[7,8,9,6,5,4,3,2]])
print(v)

[[1 3 4 5 6 6 7 4]
 [7 8 9 6 5 4 3 2]]


In [ ]:
# Get Specific element [r,c]
v[1]
v[1,3]

6

In [ ]:
# Get specific row
v[0,:]

array([1, 3, 4, 5, 6, 6, 7, 4])

In [ ]:
# Get a specific col
v[:,2]

array([4, 9])

In [ ]:
# [startindex:setindex:stepsize]
v[0,1:-1:2]

array([3, 5, 6])

In [ ]:
v[1,6]=69
v[:,2]=[4,1]

v

array([[ 1,  3,  4,  5,  6,  6,  7,  4],
       [ 7,  8,  1,  6,  5,  4, 69,  2]])

In [ ]:
# 3D arrays
d= np.array([[[2,3,4],[2,4,6]],[[1,6,3],[0,8,9]]])

In [ ]:
d[0,1,2]
d[:,1:]=[[9,3,4],[2,3]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### Intializing Different Types of Arrays

In [ ]:
# intialize with zeros
np.zeros((1,2,3,4,5))

# intialize with 1s
np.ones((4,2,2), dtype="int32")

#intialize with any number
np.full((2,2),99,dtype='float32')

# reusing intialized to fill alike
np.full_like(v,100)

array([[100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100]])

In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [20]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a[1:])
a_mul =np.array([[1,2,3,4,5],[1,4,32,22,3]])
print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)
# c= np.full((10,10,10),69)
# print(c)
# np.zeros and np.ones
# empty is different from zeros
# x_values = np.arrange(0,1005,5)
# print(x_values)
y_values = np.linspace(0,500,6)
print(y_values)
print(np.nan)
print(np.isnan(np.sqrt(-1)))
print(np.isinf(np.array([10])/0))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[2 3 4 5]
(2, 5)
2
10
int64
[  0. 100. 200. 300. 400. 500.]
nan
True
[ True]


<ipython-input-20-c2627010839e>:19: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))
<ipython-input-20-c2627010839e>:20: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf(np.array([10])/0))
