In [18]:
import numpy as np

c = np.array([2,4,5], dtype="int16")
print(c)

[2 4 5]


In [19]:
#2-D Array
d=np.array([[3.5,4.0,5.4,5.3],[1.2,8.0,9.0,6.0]])
print(d)

[[3.5 4.  5.4 5.3]
 [1.2 8.  9.  6. ]]


In [20]:
#Get Dimension
d.ndim

2

In [21]:
# Get Shape
d.shape

(2, 4)

In [22]:
# Get Type
d.dtype
c.dtype

dtype('int16')

In [23]:
# Get Size
d.itemsize

8

In [24]:
# Get Total Size
d.nbytes

64

In [25]:
v= np.array([[1,3,4,5,6,6,7,4],[7,8,9,6,5,4,3,2]])
print(v)

[[1 3 4 5 6 6 7 4]
 [7 8 9 6 5 4 3 2]]


In [26]:
# Get Specific element [r,c]
v[1]
v[1,3]

6

In [27]:
# Get specific row
v[0,:]

array([1, 3, 4, 5, 6, 6, 7, 4])

In [28]:
# Get a specific col
v[:,2]

array([4, 9])

In [29]:
# [startindex:setindex:stepsize]
v[0,1:-1:2]

array([3, 5, 6])

In [30]:
v[1,6]=69
v[:,2]=[4,1]

v

array([[ 1,  3,  4,  5,  6,  6,  7,  4],
       [ 7,  8,  1,  6,  5,  4, 69,  2]])

In [31]:
# 3D arrays
d= np.array([[[2,3,4],[2,4,6]],[[1,6,3],[0,8,9]]])

In [33]:
d[0,1,2]
d[:,1:]=[[9,3,4],[2,3]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### Intializing Different Types of Arrays

In [ ]:
# intialize with zeros
np.zeros((1,2,3,4,5))

# intialize with 1s
np.ones((4,2,2), dtype="int32")

#intialize with any number
np.full((2,2),99,dtype='float32')

# reusing intialized to fill alike
np.full_like(v,100)

array([[100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100]])

In [34]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]
