In [2]:
import numpy as np

c = np.array([2,4,5], dtype="int16")
print(c)

[2 4 5]


In [ ]:
#2-D Array
d=np.array([[3.5,4.0,5.4,5.3],[1.2,8.0,9.0,6.0]])
print(d)

[[3.5 4.  5.4 5.3]
 [1.2 8.  9.  6. ]]


In [ ]:
#Get Dimension
d.ndim

2

In [ ]:
# Get Shape
d.shape

(2, 4)

In [ ]:
# Get Type
d.dtype
c.dtype

dtype('int16')

In [ ]:
# Get Size
d.itemsize

8

In [ ]:
# Get Total Size
d.nbytes

64

In [ ]:
v= np.array([[1,3,4,5,6,6,7,4],[7,8,9,6,5,4,3,2]])
print(v)

[[1 3 4 5 6 6 7 4]
 [7 8 9 6 5 4 3 2]]


In [ ]:
# Get Specific element [r,c]
v[1]
v[1,3]

6

In [ ]:
# Get specific row
v[0,:]

array([1, 3, 4, 5, 6, 6, 7, 4])

In [ ]:
# Get a specific col
v[:,2]

array([4, 9])

In [ ]:
# [startindex:setindex:stepsize]
v[0,1:-1:2]

array([3, 5, 6])

In [ ]:
v[1,6]=69
v[:,2]=[4,1]

v

array([[ 1,  3,  4,  5,  6,  6,  7,  4],
       [ 7,  8,  1,  6,  5,  4, 69,  2]])

In [ ]:
# 3D arrays
d= np.array([[[2,3,4],[2,4,6]],[[1,6,3],[0,8,9]]])

In [ ]:
d[0,1,2]
d[:,1:]=[[9,3,4],[2,3]]

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

### Intializing Different Types of Arrays

In [ ]:
# intialize with zeros
np.zeros((1,2,3,4,5))

# intialize with 1s
np.ones((4,2,2), dtype="int32")

#intialize with any number
np.full((2,2),99,dtype='float32')

# reusing intialized to fill alike
np.full_like(v,100)

array([[100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100]])

In [ ]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


In [20]:
a=np.array([1,2,3,4,5])
print(a)
print(type(a))
print(a[1:])
a_mul =np.array([[1,2,3,4,5],[1,4,32,22,3]])
print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)
# c= np.full((10,10,10),69)
# print(c)
# np.zeros and np.ones
# empty is different from zeros
# x_values = np.arrange(0,1005,5)
# print(x_values)
y_values = np.linspace(0,500,6)
print(y_values)
print(np.nan)
# print(np.isnan(np.sqrt(-1)))
# print(np.isinf(np.array([10])/0))


[1 2 3 4 5]
<class 'numpy.ndarray'>
[2 3 4 5]
(2, 5)
2
10
int64
[  0. 100. 200. 300. 400. 500.]
nan


In [22]:
# numpy arrays are operated as vector or matrix when doing mathematical operations
# similar cant be done with python lists
f = np.array([[1,2,3],[2,5,6]])
print(np.sqrt(f)) # return the array with sqrt of each element in the place of element
print(np.append(a,[7,8,6]))
print(np.insert(a,3,[90,69]))
print(np.delete(a,1))
print(np.delete(a,1,0))
print(f.reshape(3,2))
print(f.reshape(2,3,1))
print(f.reshape(6,))
print(f.reshape(6,1))
# reshape doesnt makes any permanent changes but resize does

print(f.flatten())
print(f.ravel())
# flatten creates a copy while ravel makes permanent changes

print([v for v in f.flat])

[[1.         1.41421356 1.73205081]
 [1.41421356 2.23606798 2.44948974]]
[1 2 3 4 5 7 8 6]
[ 1  2  3 90 69  4  5]
[1 3 4 5]
[1 3 4 5]
[[1 2]
 [3 2]
 [5 6]]
[[[1]
  [2]
  [3]]

 [[2]
  [5]
  [6]]]
[1 2 3 2 5 6]
[[1]
 [2]
 [3]
 [2]
 [5]
 [6]]
[1 2 3 2 5 6]
[1 2 3 2 5 6]
[np.int64(1), np.int64(2), np.int64(3), np.int64(2), np.int64(5), np.int64(6)]


In [44]:
print(f.transpose())
# OR
print(f.T)
print(f.swapaxes(0,1)) # useful when we have higher dimension of array and we only need to make changes to two arrays
a1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a2= np.array([[11,12,14,13,15],[16,17,18,19,20]])
a3 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,14,13,15],[16,17,18,19,20]])
print(np.concatenate((a1,a2), axis=0))
print(np.concatenate((a1,a2),axis=1))
print(np.stack((a1,a2),axis=0))
print(np.vstack((a1,a2))) # does same thing as concatenate on 0 axis
print(np.hstack((a1,a2))) # does same thing as concatenate on 1 axis
print(np.split(a3,2, axis=0))
print(a3.min())
print(a3.max())
print(a3.std())
print(a3.mean())
print(a3.sum())
print(np.median(a3))

[[1 2]
 [2 5]
 [3 6]]
[[1 2]
 [2 5]
 [3 6]]
[[1 2]
 [2 5]
 [3 6]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 14 13 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 14 13 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 14 13 15]
  [16 17 18 19 20]]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 14 13 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 14 13 15]
 [ 6  7  8  9 10 16 17 18 19 20]]
[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 14, 13, 15],
       [16, 17, 18, 19, 20]])]
1
20
5.766281297335398
10.5
210
10.5


In [56]:
numbero = np.random.randint(100,size=(2,3,4))
print(numbero)
print(np.random.binomial(10,p=0.5,size=(5,10)))
print(np.random.normal(loc=170,scale=15,size=(6,7)))
print(np.random.choice([10,20,30,40,50],size=(5,10)))


[[[79 21 75 73]
  [77 88 46 76]
  [60  0  5 50]]

 [[80 40 98 51]
  [41 94 14 11]
  [44 47 66 49]]]
[[3 4 5 6 3 3 6 4 7 4]
 [5 7 5 7 6 7 6 3 5 6]
 [5 2 7 6 3 8 5 6 7 5]
 [3 4 6 5 6 5 5 2 4 7]
 [6 7 8 5 4 3 5 5 5 3]]
[[156.58320411 160.00343897 173.92180227 187.0411777  173.80586013
  168.41723239 163.07887419]
 [176.45195192 123.20426132 167.86984675 165.43342587 139.50938283
  185.2800706  162.19554465]
 [172.29363124 162.27449619 166.09160797 146.41133384 156.8694852
  165.85742269 164.86722293]
 [147.07964175 179.23006619 175.55047713 159.32928035 178.57640644
  152.02544197 160.55397476]
 [172.64657313 170.08425776 168.96640952 198.08747482 210.22279341
  171.21331283 168.51528229]
 [178.12830299 158.41817295 175.38421612 191.25441852 175.13880068
  158.02043786 145.34803217]]
[[20 20 10 20 30 40 20 10 50 40]
 [20 10 50 50 30 30 40 40 40 50]
 [20 30 10 20 10 40 50 10 50 10]
 [50 10 40 30 40 30 30 20 10 10]
 [30 40 20 20 50 10 30 20 10 50]]


In [58]:
np.save('myarray.npy',a3)

In [62]:
print(np.load("myarray.npy"))
np.savetxt("arraycsv.csv",a3,delimiter=",")

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 14 13 15]
 [16 17 18 19 20]]


In [63]:
print(np.loadtxt("arraycsv.csv",delimiter=","))

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 14. 13. 15.]
 [16. 17. 18. 19. 20.]]
